version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: careerpath_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/careerpath
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: careerpath_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: careerpath
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: careerpath_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
